# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7aea1df8d3551139d710f1a9c067cab3d87054bfed150bab8bf830e8405046789988dee931681f822951f2128b21d0956973ec45200ef974d9d44e34468673c

test:
  secret_key_base: 5cd1500e609b9092d28120170ff4f842abef31cecedfacea7875f000f5ebd91411f88ff1c038188ba141dc2354cbd7ce173640865137a0776dde190742e16ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
