# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b346f0ba39133646bef6e47f8d882590e3a95b6fb3dd65322215edb109958766416381ea9c36dc9e405fc360280b3626f9397bfbd1cb0f0395b6314cc83093d

test:
  secret_key_base: ca14be2f2a663fac93c3cba9a1e41435b7d22649e192b0934a72d90caddf0975ba5fe7dff167947577b6f4ed581676c66f3723b95c9e5581871c327f90ddd44a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
